version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "15432:5432"
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=employee_user
      - POSTGRES_PASSWORD=employee_password
      - POSTGRES_DB=employee

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
